MODEL:
  META_ARCHITECTURE: "EntityFPN"
  MASK_ON: False
  BACKBONE:
    NAME: "build_retinanet_mit_fpn_backbone"
    FREEZE_AT: -1
  MIT_BACKBONE:
    NAME: "b5"
  WEIGHTS: "pretrained_model/mit_b5_trans.pth"
  FPN:
    IN_FEATURES: ["mit1", "mit2", "mit3", "mit4"]
    TOP_LEVELS: 2
  FCOS:
    NUM_CLASSES: 1
  CONDINST:
    CLASS_AGNOSTIC: True
    TRAIN_MAX_PROPOSALS_PER_IMAGE: 80
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: False
      IN_FEATURES: ["p3", "p4", "p5"]
    MASK_HEAD:
      CLUSTER_WEIGHT: 0.5
      DYNAMIC: ["111", "110", "101", "100", "011", "010", "001"]
      DYNAMIC_WEIGHT: [1.0, 1.0, 1.0, 1.0, 0.25, 0.25, 0.25]
DATASETS:
  TRAIN: ("coco_2017_train_entity",)
  TEST: ("coco_2017_val_entity",)
SOLVER:
  OPTIMIZER: "adamw"
  WARMUP_ITERS: 1500
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 20000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
TEST:
  CLASS_AGNOSTIC: True